use strict;
use warnings;
package IO::Iron::Applications;

# ABSTRACT: Command line tools for package IO::Iron

# VERSION: generated by DZP::OurPkgVersion

=head1 DESCRIPTION

This package contains three command line tools: ironcache,
ironmq (not yet implemented) and ironworker (not yet implemented).
They are for operating the webservices with needing the WWW interface.
Some functionality has been added, such as reading or writing
from several IronCaches simultaneously. Please see the file
L<ironcache.pl|ironcache> for further documentation.

=cut

1;
