package IO::Iron::Applications::IronCache;

use 5.010_000;
use strict;
use warnings FATAL => 'all';

# Global creator
BEGIN {
	# No exports
}

# Global destructor
END {
}

# ABSTRACT: ironcache.pl command internals.

# VERSION: generated by DZP::OurPkgVersion

use App::Cmd::Setup -app;

=head2 description

Description of command.

=cut

sub description {
	return "IronCache functions";
}

1;
