package IO::Iron::Applications::IronCache;

use 5.010_000;
use strict;
use warnings FATAL => 'all';

# Global creator
BEGIN {
	# No exports
}

# Global destructor
END {
}

# ABSTRACT: ironcache.pl command internals.

# VERSION: generated by DZP::OurPkgVersion

use App::Cmd::Setup -app;

=head2 description

Description of command.

=cut

sub description {
	return "IronCache functions";
}

1;

__END__

ironmq --config delete <queue_name>
ironmq --config show <queue_name>
ironmq --config create <queue_name> --params # This doesn't do anything!
ironmq --config update <queue_name> --values
ironmq --config list queues --n 
ironmq --config list messages --queue <queue_name>
ironmq --config list alerts --queue <queue_name>
ironmq --verbose --debug --config list subscribers --queue <queue_name>

COMMON:
--config <file> 
--verbose --debug --trace
<item_key> = <wildcard or list or both: cac01??22_99,cac01??22??>
--csv = do not use the TT2 template for output, instead print comma separated variables, with legend on the first row.

ironcache list caches >STDOUT
ironcache list items <wildcard or list or both: cac01??22_99,cac01??22??>
: item parameters and contents
ironcache show cache name,name,wildcard_name >STDOUT
ironcache delete cache <cache>
: [NONE]
ironcache clear cache <cache>
: [NONE]

ironcache put item <item_key> --cache <cache> <STDIN | --value
: [NONE]
!!!ironcache increment item <item_key> --by <int> --cache <cache>
ironcache increment item <item_key> --cache <cache> <STDIN <int> | --value <int>
: [NONE]
ironcache get item <item_key> --cache <cache> >STDOUT
: only item content, one per row. Order: as given cache(s)/item(s)
ironcache delete item <item_key> --cache <cache>
: [NONE]

Use Template Toolkit for _all_ output.

--policy (a file containing info which cache and item names are accepted,
    which characters are accepted, cache:items:chars)

Use threads!
put/increment/get/delete no wildcards supported! ???
