package IO::Iron::Applications::IronCache::Templates;

use 5.010_000;
use strict;
use warnings FATAL => 'all';

# Global creator
BEGIN {
    # No exports
}

# Global destructor
END {
}

# ABSTRACT: ironcache.pl command internals: functionality.

# VERSION: generated by DZP::OurPkgVersion

my $LINEFEED = qq{\n};

sub _list_caches_template {
    return '[% FOREACH cache_name IN data.caches.keys.sort %]'
            . '[% cache_name %]' . $LINEFEED 
            . '[% END %]'
            ;
}

sub _list_items_template {
    return "[% USE timestamp = date(format => '%Y-%B-%d') %][% FILTER format('%-30s') %]Cache[% END %][% FILTER format('%-20s') %]Item[% END %][% FILTER format('%-21s') %]expires[% END %][% IF instructions.show_value %]value[% END %]" . $LINEFEED
            . "[% FOREACH cache_name IN data.caches.keys.sort %]"
            . "[% cache = data.caches.item(cache_name) %]"
            . "[% IF cache.error %]"
            . "[% cache_name %]:[% cache.error %]" . $LINEFEED
            . "[% ELSE %]"
            . "[% FOREACH item_key IN cache.items.keys.sort %]"
            . "[% item = cache.items.item(item_key) %]"
            . "[% IF item.error %]"
            . "[% FILTER format('%-30s') %][% FILTER truncate(29) %][% cache_name %][% END %][% END %]"
            . "[% FILTER format('%-20s') %][% item_key %][% END %]"
            . "[% FILTER format('%-21s') %] [% END %]"
            . "[% item.error %]" . $LINEFEED
            . "[% ELSE %]"
            . "[% FILTER format('%-30s') %][% FILTER truncate(29) %][% cache_name %][% END %][% END %]"
            . "[% FILTER format('%-20s') %][% item_key %][% END %]"
            . "[% FILTER format('%-21s') %][% item.expires %][% END %]"
            . "[% IF instructions.show_value %][% item.value %][% END %]" . $LINEFEED
            . "[% END %][%# /IF item.error %]"
            . "[% END %][%# /FOREACH %]"
            . "[% END %][%# /IF cache.error %]"
            . "[% END %][%# /FOREACH %]"
            ;
}

sub _show_cache_template {
    return "[% USE timestamp = date(format => '%Y-%B-%d') %][% FILTER format('%-30s') %]Name[% END %][% FILTER format('%-25s') %]id[% END %][% FILTER format('%-5s') %]size[% END %][% FILTER format('%-6s') %]dsize[% END %][% FILTER format('%-12s') %]created[% END %]" . $LINEFEED
            . "[% FOREACH cache_name IN data.caches.keys.sort %]"
            . "[% FILTER format('%-30s') %][% FILTER truncate(29) %][% cache_name %][% END %][% END %]"
            . "[% FILTER format('%-25s') %][% data.caches.item(cache_name).id %][% END %]"
            . "[% FILTER format('%-5s') %][% data.caches.item(cache_name).size %][% END %]"
            . "[% FILTER format('%-6s') %][% data.caches.item(cache_name).data_size %][% END %]"
            . "[% FILTER format('%-12s') %][% timestamp.format(data.caches.item(cache_name).created_at) %][% END %]" . $LINEFEED
            . "[% END %]"
            ;
}

# Attn. These four functions which operate "simple" operations on items
# do not have anything to pring, except get_item 
# which only outputs the item's (or items') content.
sub _put_item_template {
    return '';
}

sub _increment_item_template {
    return '';
}

sub _delete_item_template {
    return '';
}

sub _get_item_template {
    return ""
# printing is done from inside the executing function!
#            . "[% FOREACH cache_name IN data.caches.keys.sort %]"
#            . "[% cache = data.caches.item(cache_name) %]"
#            . "[% IF cache.error %]"
#            . "[% cache_name %]:[% cache.error %]" . $LINEFEED
#            . "[% ELSE %]"
#            . "[% FOREACH item_key IN cache.items.keys.sort %]"
#            . "[% item = cache.items.item(item_key) %]"
#            . "[% IF item.error %]"
#            . "[% item_key %]:[% item.error %]"
#            . "[% ELSE %]"
#            . "[% item.value %]"
#            . "[% END %][%# /IF item.error %]" . $LINEFEED # Attn. The linefeed is here!
#            . "[% END %][%# /FOREACH %]"
#            . "[% END %][%# /IF cache.error %]"
#            . "[% END %][%# /FOREACH %]"
            ;
}

1;
